// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { GetContextData, GetContextErrors, GetContextResponses, GetResearchData, GetResearchErrors, GetResearchResponses, HealthData, HealthErrors, HealthResponses, ListAccountSnapshotsData, ListAccountSnapshotsErrors, ListAccountSnapshotsResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Snapshots
 */
export const listAccountSnapshots = <ThrowOnError extends boolean = false>(options?: Options<ListAccountSnapshotsData, ThrowOnError>): RequestResult<ListAccountSnapshotsResponses, ListAccountSnapshotsErrors, ThrowOnError> => (options?.client ?? client).get<ListAccountSnapshotsResponses, ListAccountSnapshotsErrors, ThrowOnError>({ url: '/api/v1/account-snapshots', ...options });

/**
 * Context
 */
export const getContext = <ThrowOnError extends boolean = false>(options?: Options<GetContextData, ThrowOnError>): RequestResult<GetContextResponses, GetContextErrors, ThrowOnError> => (options?.client ?? client).get<GetContextResponses, GetContextErrors, ThrowOnError>({ url: '/api/v1/context', ...options });

/**
 * Health
 */
export const health = <ThrowOnError extends boolean = false>(options?: Options<HealthData, ThrowOnError>): RequestResult<HealthResponses, HealthErrors, ThrowOnError> => (options?.client ?? client).get<HealthResponses, HealthErrors, ThrowOnError>({ url: '/api/v1/health', ...options });

/**
 * Research Record
 */
export const getResearch = <ThrowOnError extends boolean = false>(options: Options<GetResearchData, ThrowOnError>): RequestResult<GetResearchResponses, GetResearchErrors, ThrowOnError> => (options.client ?? client).get<GetResearchResponses, GetResearchErrors, ThrowOnError>({ url: '/api/v1/research/{id}', ...options });
