// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { CancelJobData, CancelJobErrors, CancelJobResponses, CreateCapitalPlanData, CreateCapitalPlanErrors, CreateCapitalPlanResponses, CreateInvestigationData, CreateInvestigationErrors, CreateInvestigationResponses, GetCapitalPlanData, GetCapitalPlanErrors, GetCapitalPlanResponses, GetContextData, GetContextErrors, GetContextResponses, GetFundingData, GetFundingErrors, GetFundingResponses, GetInvestigationData, GetInvestigationErrors, GetInvestigationResponses, GetJobData, GetJobErrors, GetJobResponses, GetMarketViewData, GetMarketViewErrors, GetMarketViewResponses, GetResearchData, GetResearchErrors, GetResearchResponses, HealthData, HealthErrors, HealthResponses, JobServiceStatusData, JobServiceStatusErrors, JobServiceStatusResponses, ListAccountSnapshotsData, ListAccountSnapshotsErrors, ListAccountSnapshotsResponses, ListCapitalPlansData, ListCapitalPlansErrors, ListCapitalPlansResponses, ListInvestigationsData, ListInvestigationsErrors, ListInvestigationsResponses, ListJobsData, ListJobsErrors, ListJobsResponses, ListMarketCapturesData, ListMarketCapturesErrors, ListMarketCapturesResponses, PauseInvestigationData, PauseInvestigationErrors, PauseInvestigationResponses, PreviewCapitalPlanData, PreviewCapitalPlanErrors, PreviewCapitalPlanResponses, RefreshFundingData, RefreshFundingErrors, RefreshFundingResponses, ReleaseFundingReservationData, ReleaseFundingReservationErrors, ReleaseFundingReservationResponses, ReserveCapitalPlanData, ReserveCapitalPlanErrors, ReserveCapitalPlanResponses, ReviseInvestigationData, ReviseInvestigationErrors, ReviseInvestigationResponses, SubmitJobData, SubmitJobErrors, SubmitJobResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Snapshots
 */
export const listAccountSnapshots = <ThrowOnError extends boolean = false>(options?: Options<ListAccountSnapshotsData, ThrowOnError>): RequestResult<ListAccountSnapshotsResponses, ListAccountSnapshotsErrors, ThrowOnError> => (options?.client ?? client).get<ListAccountSnapshotsResponses, ListAccountSnapshotsErrors, ThrowOnError>({ url: '/api/v1/account-snapshots', ...options });

/**
 * List Capital Plans
 */
export const listCapitalPlans = <ThrowOnError extends boolean = false>(options?: Options<ListCapitalPlansData, ThrowOnError>): RequestResult<ListCapitalPlansResponses, ListCapitalPlansErrors, ThrowOnError> => (options?.client ?? client).get<ListCapitalPlansResponses, ListCapitalPlansErrors, ThrowOnError>({ url: '/api/v1/capital-plans', ...options });

/**
 * Create Capital Plan
 */
export const createCapitalPlan = <ThrowOnError extends boolean = false>(options: Options<CreateCapitalPlanData, ThrowOnError>): RequestResult<CreateCapitalPlanResponses, CreateCapitalPlanErrors, ThrowOnError> => (options.client ?? client).post<CreateCapitalPlanResponses, CreateCapitalPlanErrors, ThrowOnError>({
    url: '/api/v1/capital-plans',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Preview Capital Plan
 */
export const previewCapitalPlan = <ThrowOnError extends boolean = false>(options: Options<PreviewCapitalPlanData, ThrowOnError>): RequestResult<PreviewCapitalPlanResponses, PreviewCapitalPlanErrors, ThrowOnError> => (options.client ?? client).post<PreviewCapitalPlanResponses, PreviewCapitalPlanErrors, ThrowOnError>({
    url: '/api/v1/capital-plans/preview',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get Capital Plan
 */
export const getCapitalPlan = <ThrowOnError extends boolean = false>(options: Options<GetCapitalPlanData, ThrowOnError>): RequestResult<GetCapitalPlanResponses, GetCapitalPlanErrors, ThrowOnError> => (options.client ?? client).get<GetCapitalPlanResponses, GetCapitalPlanErrors, ThrowOnError>({ url: '/api/v1/capital-plans/{id}', ...options });

/**
 * Reserve Capital Plan
 */
export const reserveCapitalPlan = <ThrowOnError extends boolean = false>(options: Options<ReserveCapitalPlanData, ThrowOnError>): RequestResult<ReserveCapitalPlanResponses, ReserveCapitalPlanErrors, ThrowOnError> => (options.client ?? client).post<ReserveCapitalPlanResponses, ReserveCapitalPlanErrors, ThrowOnError>({
    url: '/api/v1/capital-plans/{id}/reserve',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Context
 */
export const getContext = <ThrowOnError extends boolean = false>(options?: Options<GetContextData, ThrowOnError>): RequestResult<GetContextResponses, GetContextErrors, ThrowOnError> => (options?.client ?? client).get<GetContextResponses, GetContextErrors, ThrowOnError>({ url: '/api/v1/context', ...options });

/**
 * Get Funding
 */
export const getFunding = <ThrowOnError extends boolean = false>(options: Options<GetFundingData, ThrowOnError>): RequestResult<GetFundingResponses, GetFundingErrors, ThrowOnError> => (options.client ?? client).get<GetFundingResponses, GetFundingErrors, ThrowOnError>({ url: '/api/v1/funding', ...options });

/**
 * Refresh Funding
 */
export const refreshFunding = <ThrowOnError extends boolean = false>(options: Options<RefreshFundingData, ThrowOnError>): RequestResult<RefreshFundingResponses, RefreshFundingErrors, ThrowOnError> => (options.client ?? client).post<RefreshFundingResponses, RefreshFundingErrors, ThrowOnError>({
    url: '/api/v1/funding/refresh',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Release Funding Reservation
 */
export const releaseFundingReservation = <ThrowOnError extends boolean = false>(options: Options<ReleaseFundingReservationData, ThrowOnError>): RequestResult<ReleaseFundingReservationResponses, ReleaseFundingReservationErrors, ThrowOnError> => (options.client ?? client).post<ReleaseFundingReservationResponses, ReleaseFundingReservationErrors, ThrowOnError>({ url: '/api/v1/funding/reservations/{id}/release', ...options });

/**
 * Health
 */
export const health = <ThrowOnError extends boolean = false>(options?: Options<HealthData, ThrowOnError>): RequestResult<HealthResponses, HealthErrors, ThrowOnError> => (options?.client ?? client).get<HealthResponses, HealthErrors, ThrowOnError>({ url: '/api/v1/health', ...options });

/**
 * List Investigations
 */
export const listInvestigations = <ThrowOnError extends boolean = false>(options?: Options<ListInvestigationsData, ThrowOnError>): RequestResult<ListInvestigationsResponses, ListInvestigationsErrors, ThrowOnError> => (options?.client ?? client).get<ListInvestigationsResponses, ListInvestigationsErrors, ThrowOnError>({ url: '/api/v1/investigations', ...options });

/**
 * Create Investigation
 */
export const createInvestigation = <ThrowOnError extends boolean = false>(options: Options<CreateInvestigationData, ThrowOnError>): RequestResult<CreateInvestigationResponses, CreateInvestigationErrors, ThrowOnError> => (options.client ?? client).post<CreateInvestigationResponses, CreateInvestigationErrors, ThrowOnError>({
    url: '/api/v1/investigations',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get Investigation
 */
export const getInvestigation = <ThrowOnError extends boolean = false>(options: Options<GetInvestigationData, ThrowOnError>): RequestResult<GetInvestigationResponses, GetInvestigationErrors, ThrowOnError> => (options.client ?? client).get<GetInvestigationResponses, GetInvestigationErrors, ThrowOnError>({ url: '/api/v1/investigations/{id}', ...options });

/**
 * Pause Investigation
 */
export const pauseInvestigation = <ThrowOnError extends boolean = false>(options: Options<PauseInvestigationData, ThrowOnError>): RequestResult<PauseInvestigationResponses, PauseInvestigationErrors, ThrowOnError> => (options.client ?? client).post<PauseInvestigationResponses, PauseInvestigationErrors, ThrowOnError>({
    url: '/api/v1/investigations/{id}/pause',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Revise Investigation
 */
export const reviseInvestigation = <ThrowOnError extends boolean = false>(options: Options<ReviseInvestigationData, ThrowOnError>): RequestResult<ReviseInvestigationResponses, ReviseInvestigationErrors, ThrowOnError> => (options.client ?? client).post<ReviseInvestigationResponses, ReviseInvestigationErrors, ThrowOnError>({
    url: '/api/v1/investigations/{id}/revisions',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List Jobs
 */
export const listJobs = <ThrowOnError extends boolean = false>(options?: Options<ListJobsData, ThrowOnError>): RequestResult<ListJobsResponses, ListJobsErrors, ThrowOnError> => (options?.client ?? client).get<ListJobsResponses, ListJobsErrors, ThrowOnError>({ url: '/api/v1/jobs', ...options });

/**
 * Submit
 */
export const submitJob = <ThrowOnError extends boolean = false>(options: Options<SubmitJobData, ThrowOnError>): RequestResult<SubmitJobResponses, SubmitJobErrors, ThrowOnError> => (options.client ?? client).post<SubmitJobResponses, SubmitJobErrors, ThrowOnError>({
    url: '/api/v1/jobs',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Status
 */
export const jobServiceStatus = <ThrowOnError extends boolean = false>(options?: Options<JobServiceStatusData, ThrowOnError>): RequestResult<JobServiceStatusResponses, JobServiceStatusErrors, ThrowOnError> => (options?.client ?? client).get<JobServiceStatusResponses, JobServiceStatusErrors, ThrowOnError>({ url: '/api/v1/jobs/status', ...options });

/**
 * Get Job
 */
export const getJob = <ThrowOnError extends boolean = false>(options: Options<GetJobData, ThrowOnError>): RequestResult<GetJobResponses, GetJobErrors, ThrowOnError> => (options.client ?? client).get<GetJobResponses, GetJobErrors, ThrowOnError>({ url: '/api/v1/jobs/{id}', ...options });

/**
 * Cancel Job
 */
export const cancelJob = <ThrowOnError extends boolean = false>(options: Options<CancelJobData, ThrowOnError>): RequestResult<CancelJobResponses, CancelJobErrors, ThrowOnError> => (options.client ?? client).post<CancelJobResponses, CancelJobErrors, ThrowOnError>({ url: '/api/v1/jobs/{id}/cancel', ...options });

/**
 * List Market Captures
 */
export const listMarketCaptures = <ThrowOnError extends boolean = false>(options?: Options<ListMarketCapturesData, ThrowOnError>): RequestResult<ListMarketCapturesResponses, ListMarketCapturesErrors, ThrowOnError> => (options?.client ?? client).get<ListMarketCapturesResponses, ListMarketCapturesErrors, ThrowOnError>({ url: '/api/v1/market/catalog', ...options });

/**
 * Get Market View
 */
export const getMarketView = <ThrowOnError extends boolean = false>(options: Options<GetMarketViewData, ThrowOnError>): RequestResult<GetMarketViewResponses, GetMarketViewErrors, ThrowOnError> => (options.client ?? client).post<GetMarketViewResponses, GetMarketViewErrors, ThrowOnError>({
    url: '/api/v1/market/view',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Research Record
 */
export const getResearch = <ThrowOnError extends boolean = false>(options: Options<GetResearchData, ThrowOnError>): RequestResult<GetResearchResponses, GetResearchErrors, ThrowOnError> => (options.client ?? client).get<GetResearchResponses, GetResearchErrors, ThrowOnError>({ url: '/api/v1/research/{id}', ...options });
