// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * AccountCoverage
 */
export type AccountCoverage = {
    /**
     * All Pending Account Commitments
     */
    all_pending_account_commitments: false;
    /**
     * Atomic Account Instant
     */
    atomic_account_instant: false;
    /**
     * Buying Power Semantics
     */
    buying_power_semantics: string;
    /**
     * Execution Ready
     */
    execution_ready: false;
    /**
     * Historical Dataset
     */
    historical_dataset: false;
    /**
     * Holdings Scope
     */
    holdings_scope: string;
    /**
     * Observation Kind
     */
    observation_kind: 'current_account_observation';
    /**
     * Open Order Scope
     */
    open_order_scope: string;
    /**
     * Total Account Equity Known
     */
    total_account_equity_known: false;
    /**
     * Verified Cash Balances
     */
    verified_cash_balances: false;
};

/**
 * AccountSnapshot
 */
export type AccountSnapshot = {
    /**
     * Account Seq
     */
    account_seq: string;
    /**
     * Account Type
     */
    account_type: string;
    cash_balances: CashBalances;
    cash_buying_power: BuyingPower;
    /**
     * Collection Completed At
     */
    collection_completed_at: string;
    /**
     * Collection Started At
     */
    collection_started_at: string;
    /**
     * Commissions
     */
    commissions: Array<Commission>;
    /**
     * Contract Sha256
     */
    contract_sha256: string;
    coverage: AccountCoverage;
    holdings: HoldingsOverview;
    /**
     * Open Orders
     */
    open_orders: Array<OpenOrder>;
    /**
     * Source Observations
     */
    source_observations: Array<SourceObservation>;
    /**
     * Warnings
     */
    warnings: Array<string>;
};

/**
 * AccountSnapshotsResponse
 */
export type AccountSnapshotsResponse = {
    /**
     * Items
     */
    items: Array<SnapshotSummary>;
};

/**
 * BuyingPower
 */
export type BuyingPower = {
    /**
     * Krw
     */
    KRW: string;
    /**
     * Usd
     */
    USD: string;
};

/**
 * CandleRevision
 */
export type CandleRevision = {
    /**
     * Capture Ids
     */
    capture_ids: Array<string>;
    /**
     * Close
     */
    close: string;
    /**
     * High
     */
    high: string;
    /**
     * Id
     */
    id: string;
    /**
     * Last Observed At
     */
    last_observed_at: string;
    /**
     * Low
     */
    low: string;
    /**
     * Observed At
     */
    observed_at: string;
    /**
     * Open
     */
    open: string;
    /**
     * Volume
     */
    volume: string;
};

/**
 * CashBalances
 */
export type CashBalances = {
    /**
     * Krw
     */
    KRW: null;
    /**
     * Usd
     */
    USD: null;
};

/**
 * Commission
 */
export type Commission = {
    /**
     * Commissionrate
     */
    commissionRate: string;
    /**
     * Enddate
     */
    endDate?: string | null;
    /**
     * Marketcountry
     */
    marketCountry: string;
    /**
     * Startdate
     */
    startDate?: string | null;
};

/**
 * Cost
 */
export type Cost = {
    /**
     * Commission
     */
    commission: string;
    /**
     * Tax
     */
    tax?: string | null;
};

/**
 * CurrencyAmounts
 */
export type CurrencyAmounts = {
    /**
     * Krw
     */
    krw: string;
    /**
     * Usd
     */
    usd?: string | null;
};

/**
 * DailyProfitLoss
 */
export type DailyProfitLoss = {
    /**
     * Amount
     */
    amount: string;
    /**
     * Rate
     */
    rate: string;
};

/**
 * DecisionPayload
 */
export type DecisionPayload = {
    /**
     * Account Snapshot Id
     */
    account_snapshot_id: string | null;
    /**
     * Alternatives
     */
    alternatives: Array<string>;
    /**
     * Evidence Ids
     */
    evidence_ids: Array<string>;
    /**
     * Hypothesis Ids
     */
    hypothesis_ids: Array<string>;
    /**
     * Objective
     */
    objective: string;
    /**
     * Prior Decision Id
     */
    prior_decision_id?: string | null;
    /**
     * Proposed Actions
     */
    proposed_actions: Array<ProposedAction>;
    /**
     * Rationale
     */
    rationale: string;
    /**
     * Review After
     */
    review_after: string;
    /**
     * Sizing Validated
     */
    sizing_validated: false;
    /**
     * Status
     */
    status: 'proposed';
    /**
     * Unresolved Questions
     */
    unresolved_questions: Array<string>;
};

/**
 * DecisionRecord
 */
export type DecisionRecord = {
    author: ResearchAuthor;
    /**
     * Kind
     */
    kind: 'decision';
    /**
     * Mode
     */
    mode: 'prospective' | 'retrospective' | 'synthetic';
    payload: DecisionPayload;
    /**
     * Recorded At
     */
    recorded_at: string;
    /**
     * Schema Version
     */
    schema_version: 1;
};

/**
 * ErrorDetail
 */
export type ErrorDetail = {
    /**
     * Code
     */
    code: string;
    /**
     * Message
     */
    message: string;
};

/**
 * ErrorResponse
 */
export type ErrorResponse = {
    error: ErrorDetail;
};

/**
 * EvidenceArtifact
 */
export type EvidenceArtifact = {
    /**
     * Id
     */
    id: string;
    /**
     * Store
     */
    store: 'account' | 'market_capture';
};

/**
 * EvidencePayload
 */
export type EvidencePayload = {
    artifact?: EvidenceArtifact | null;
    /**
     * Claim
     */
    claim: string;
    /**
     * Excerpt
     */
    excerpt?: string | null;
    market_event?: MarketEvent | null;
    /**
     * Retrieved At
     */
    retrieved_at: string;
    /**
     * Source Kind
     */
    source_kind: 'web' | 'document' | 'provider' | 'user';
    /**
     * Source Locator
     */
    source_locator: string;
    /**
     * Source Published At
     */
    source_published_at: string | null;
    /**
     * Verification
     */
    verification: 'user_supplied' | 'provider_capture' | 'unverified';
};

/**
 * EvidenceRecord
 */
export type EvidenceRecord = {
    author: ResearchAuthor;
    /**
     * Kind
     */
    kind: 'evidence';
    /**
     * Mode
     */
    mode: 'prospective' | 'retrospective' | 'synthetic';
    payload: EvidencePayload;
    /**
     * Recorded At
     */
    recorded_at: string;
    /**
     * Schema Version
     */
    schema_version: 1;
};

/**
 * HealthResponse
 */
export type HealthResponse = {
    /**
     * Jobs Enabled
     */
    jobs_enabled: boolean;
    /**
     * Orders Enabled
     */
    orders_enabled: false;
    /**
     * Read Only
     */
    read_only: boolean;
    /**
     * Service
     */
    service: 'trading-investment-web';
    /**
     * Status
     */
    status: 'ok';
    /**
     * Synthetic
     */
    synthetic: boolean;
};

/**
 * Holding
 */
export type Holding = {
    /**
     * Averagepurchaseprice
     */
    averagePurchasePrice: string;
    cost: Cost;
    /**
     * Currency
     */
    currency: string;
    dailyProfitLoss: DailyProfitLoss;
    /**
     * Lastprice
     */
    lastPrice: string;
    /**
     * Marketcountry
     */
    marketCountry: string;
    marketValue: MarketValue;
    /**
     * Name
     */
    name: string;
    profitLoss: ProfitLoss;
    /**
     * Quantity
     */
    quantity: string;
    /**
     * Symbol
     */
    symbol: string;
};

/**
 * HoldingsOverview
 */
export type HoldingsOverview = {
    dailyProfitLoss: OverviewDailyProfitLoss;
    /**
     * Items
     */
    items: Array<Holding>;
    marketValue: OverviewMarketValue;
    profitLoss: OverviewProfitLoss;
    totalPurchaseAmount: CurrencyAmounts;
};

/**
 * HypothesisPayload
 */
export type HypothesisPayload = {
    /**
     * Invalidation Conditions
     */
    invalidation_conditions: Array<string>;
    /**
     * Opposing Evidence Ids
     */
    opposing_evidence_ids: Array<string>;
    /**
     * Review Triggers
     */
    review_triggers: Array<string>;
    /**
     * Subject
     */
    subject: string;
    /**
     * Supersedes Id
     */
    supersedes_id?: string | null;
    /**
     * Supporting Evidence Ids
     */
    supporting_evidence_ids: Array<string>;
    /**
     * Thesis
     */
    thesis: string;
    /**
     * Uncertainties
     */
    uncertainties: Array<string>;
};

/**
 * HypothesisRecord
 */
export type HypothesisRecord = {
    author: ResearchAuthor;
    /**
     * Kind
     */
    kind: 'hypothesis';
    /**
     * Mode
     */
    mode: 'prospective' | 'retrospective' | 'synthetic';
    payload: HypothesisPayload;
    /**
     * Recorded At
     */
    recorded_at: string;
    /**
     * Schema Version
     */
    schema_version: 1;
};

/**
 * InvestigationCondition
 */
export type InvestigationCondition = {
    /**
     * Kind
     */
    kind: 'evidence' | 'market';
    /**
     * Symbol
     */
    symbol: string | null;
};

/**
 * InvestigationCreate
 */
export type InvestigationCreate = {
    /**
     * Capture Ids
     */
    capture_ids?: Array<string>;
    /**
     * Evidence Ids
     */
    evidence_ids?: Array<string>;
    /**
     * Mode
     */
    mode?: 'prospective' | 'retrospective' | 'synthetic';
    /**
     * Purpose
     */
    purpose: string;
    /**
     * Request Key
     */
    request_key: string;
    /**
     * Snapshot Id
     */
    snapshot_id?: string | null;
    /**
     * Symbols
     */
    symbols?: Array<string>;
};

/**
 * InvestigationInput
 */
export type InvestigationInput = {
    /**
     * As Of
     */
    as_of: string;
    /**
     * Capture Ids
     */
    capture_ids: Array<string>;
    /**
     * Evidence Ids
     */
    evidence_ids: Array<string>;
    /**
     * Input Id
     */
    input_id: string;
    /**
     * Mode
     */
    mode: 'prospective' | 'retrospective' | 'synthetic';
    /**
     * Purpose
     */
    purpose: string;
    /**
     * Snapshot Id
     */
    snapshot_id: string | null;
    /**
     * Symbols
     */
    symbols: Array<string>;
};

/**
 * InvestigationList
 */
export type InvestigationList = {
    /**
     * Items
     */
    items: Array<InvestigationView>;
};

/**
 * InvestigationOpportunity
 */
export type InvestigationOpportunity = {
    /**
     * Action
     */
    action: 'buy' | 'add' | 'trim' | 'sell' | 'hold' | 'avoid' | 'research' | 'watch' | 'wait';
    /**
     * Evidence Ids
     */
    evidence_ids: Array<string>;
    /**
     * Market
     */
    market: 'KR' | 'US';
    /**
     * Rationale
     */
    rationale: string;
    /**
     * Symbol
     */
    symbol: string;
};

/**
 * InvestigationOutput
 */
export type InvestigationOutput = {
    /**
     * Alternatives
     */
    alternatives: Array<string>;
    /**
     * Opportunities
     */
    opportunities: Array<InvestigationOpportunity>;
    /**
     * Opposing Evidence
     */
    opposing_evidence: Array<string>;
    /**
     * Rationale
     */
    rationale: string;
    /**
     * Research Requests
     */
    research_requests: Array<{
        [key: string]: unknown;
    }>;
    /**
     * Review After
     */
    review_after: string | null;
    /**
     * Review Conditions
     */
    review_conditions: Array<InvestigationCondition>;
    /**
     * Source Findings
     */
    source_findings: Array<InvestigationSourceFinding>;
    /**
     * Summary
     */
    summary: string;
    /**
     * Uncertainties
     */
    uncertainties: Array<string>;
};

/**
 * InvestigationPause
 */
export type InvestigationPause = {
    /**
     * Expected Revision
     */
    expected_revision: number;
};

/**
 * InvestigationResponse
 */
export type InvestigationResponse = {
    active_job: JobView | null;
    investigation: InvestigationView;
    /**
     * Latest Execution
     */
    latest_execution: {
        [key: string]: unknown;
    } | null;
    latest_output: InvestigationOutput | null;
    /**
     * Research Jobs
     */
    research_jobs?: Array<JobView>;
};

/**
 * InvestigationRevise
 */
export type InvestigationRevise = {
    /**
     * Capture Ids
     */
    capture_ids?: Array<string>;
    /**
     * Evidence Ids
     */
    evidence_ids?: Array<string>;
    /**
     * Expected Revision
     */
    expected_revision: number;
    /**
     * Mode
     */
    mode?: 'prospective' | 'retrospective' | 'synthetic';
    /**
     * Purpose
     */
    purpose: string;
    /**
     * Request Key
     */
    request_key: string;
    /**
     * Snapshot Id
     */
    snapshot_id?: string | null;
    /**
     * Symbols
     */
    symbols?: Array<string>;
};

/**
 * InvestigationRevision
 */
export type InvestigationRevision = {
    /**
     * Completed At
     */
    completed_at: string | null;
    context_input: InvestigationInput;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Input Sha256
     */
    input_sha256: string;
    /**
     * Job Id
     */
    job_id: string;
    /**
     * Number
     */
    number: number;
    /**
     * Request Key
     */
    request_key: string;
    /**
     * Result
     */
    result: {
        [key: string]: unknown;
    } | null;
    /**
     * Trigger Kind
     */
    trigger_kind: string;
};

/**
 * InvestigationSourceFinding
 */
export type InvestigationSourceFinding = {
    /**
     * Claim
     */
    claim: string;
    /**
     * Source Published At
     */
    source_published_at: string | null;
    /**
     * Title
     */
    title: string;
    /**
     * Url
     */
    url: string;
};

/**
 * InvestigationView
 */
export type InvestigationView = {
    /**
     * Active Job Id
     */
    active_job_id: string | null;
    context_input: InvestigationInput;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Current Revision
     */
    current_revision: number;
    /**
     * Event Conditions
     */
    event_conditions: Array<{
        [key: string]: unknown;
    }>;
    /**
     * Id
     */
    id: string;
    /**
     * Latest Completed Revision
     */
    latest_completed_revision: number | null;
    /**
     * Latest Result
     */
    latest_result: {
        [key: string]: unknown;
    } | null;
    /**
     * Next Review At
     */
    next_review_at: string | null;
    /**
     * Omitted Revision Count
     */
    omitted_revision_count: number;
    /**
     * Request Key
     */
    request_key: string;
    /**
     * Revisions
     */
    revisions: Array<InvestigationRevision>;
    /**
     * Status
     */
    status: 'active' | 'paused';
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Workspace Key
     */
    workspace_key: string;
};

/**
 * InvestmentContext
 */
export type InvestmentContext = {
    account: SelectedAccount | null;
    /**
     * Active Decision Ids
     */
    active_decision_ids: Array<string>;
    /**
     * Context Kind
     */
    context_kind: 'current_research_context';
    /**
     * Eligible Record Count
     */
    eligible_record_count: number;
    /**
     * Exported Record Count
     */
    exported_record_count: number;
    /**
     * Future Record Count
     */
    future_record_count: number;
    /**
     * Generated At
     */
    generated_at: string;
    /**
     * Historical Reproducibility
     */
    historical_reproducibility: false;
    /**
     * Omitted Record Ids
     */
    omitted_record_ids: Array<string>;
    /**
     * Omitted References
     */
    omitted_references: Array<OmittedReference>;
    /**
     * Orders Enabled
     */
    orders_enabled: false;
    /**
     * Records
     */
    records: Array<ResearchResponse>;
    /**
     * Retired Decision Ids
     */
    retired_decision_ids: Array<string>;
    /**
     * Review Queue
     */
    review_queue: Array<ReviewQueueItem>;
    /**
     * Schema Version
     */
    schema_version: 1;
    /**
     * Sizing Validated
     */
    sizing_validated: false;
    /**
     * Snapshot Freshness
     */
    snapshot_freshness: ({
        status: 'not_selected';
    } & UnselectedFreshness) | ({
        status: 'fresh' | 'future' | 'stale';
    } & SelectedFreshness);
    /**
     * Truncated Count
     */
    truncated_count: number;
    /**
     * Trust Instructions
     */
    trust_instructions: Array<string>;
    /**
     * Unresolved Questions
     */
    unresolved_questions: Array<UnresolvedQuestions>;
};

/**
 * JobAttempt
 */
export type JobAttempt = {
    /**
     * Error Code
     */
    error_code: string | null;
    /**
     * Finished At
     */
    finished_at: string | null;
    /**
     * Heartbeat At
     */
    heartbeat_at: string;
    /**
     * Number
     */
    number: number;
    /**
     * Owner
     */
    owner: string;
    /**
     * Started At
     */
    started_at: string;
    /**
     * Status
     */
    status: string;
};

/**
 * JobList
 */
export type JobList = {
    /**
     * Items
     */
    items: Array<JobView>;
};

/**
 * JobResponse
 */
export type JobResponse = {
    job: JobView;
};

/**
 * JobServiceStatus
 */
export type JobServiceStatus = {
    /**
     * Enabled
     */
    enabled: boolean;
};

/**
 * JobSubmission
 */
export type JobSubmission = {
    /**
     * Available At
     */
    available_at?: string | null;
    /**
     * Kind
     */
    kind: 'research-context' | 'account-sync' | 'market-capture';
    /**
     * Max Attempts
     */
    max_attempts?: number;
    /**
     * Parameters
     */
    parameters: {
        [key: string]: unknown;
    };
    /**
     * Request Key
     */
    request_key: string;
};

/**
 * JobView
 */
export type JobView = {
    /**
     * Attempt Count
     */
    attempt_count: number;
    /**
     * Attempts
     */
    attempts?: Array<JobAttempt>;
    /**
     * Available At
     */
    available_at: string;
    /**
     * Cancel Requested
     */
    cancel_requested: boolean;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Error Code
     */
    error_code: string | null;
    /**
     * Finished At
     */
    finished_at: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Kind
     */
    kind: string;
    /**
     * Lease Expires At
     */
    lease_expires_at: string | null;
    /**
     * Max Attempts
     */
    max_attempts: number;
    /**
     * Parameters
     */
    parameters: {
        [key: string]: unknown;
    };
    /**
     * Request Key
     */
    request_key: string;
    /**
     * Result
     */
    result: {
        [key: string]: unknown;
    } | null;
    /**
     * Status
     */
    status: 'queued' | 'running' | 'succeeded' | 'failed' | 'cancelled';
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Workspace Key
     */
    workspace_key: string;
};

/**
 * MarketCaptureSummary
 */
export type MarketCaptureSummary = {
    /**
     * Adjusted
     */
    adjusted: boolean | null;
    /**
     * Candle Count
     */
    candle_count: number | null;
    /**
     * Capture Id
     */
    capture_id: string;
    /**
     * Currencies
     */
    currencies: Array<string>;
    /**
     * Endpoint
     */
    endpoint: string;
    /**
     * Interval
     */
    interval: string | null;
    /**
     * Reason
     */
    reason: string | null;
    /**
     * Response Contract Sha256
     */
    response_contract_sha256: string | null;
    /**
     * Retrieved At
     */
    retrieved_at: string;
    /**
     * Status
     */
    status: 'supported' | 'unsupported';
    /**
     * Symbol
     */
    symbol: string | null;
};

/**
 * MarketCatalog
 */
export type MarketCatalog = {
    /**
     * Invalid Count
     */
    invalid_count: number;
    /**
     * Items
     */
    items: Array<MarketCaptureSummary>;
    /**
     * Supported Count
     */
    supported_count: number;
    /**
     * Total Count
     */
    total_count: number;
    /**
     * Truncated Count
     */
    truncated_count: number;
    /**
     * Unsupported Count
     */
    unsupported_count: number;
};

/**
 * MarketEvent
 */
export type MarketEvent = {
    /**
     * Event Kind
     */
    event_kind: 'price' | 'earnings' | 'filing' | 'news' | 'macro' | 'other';
    /**
     * Market
     */
    market: 'KR' | 'US';
    /**
     * Occurred At
     */
    occurred_at: string | null;
    /**
     * Symbol
     */
    symbol: string;
};

/**
 * MarketEvidenceEvent
 */
export type MarketEvidenceEvent = {
    /**
     * Claim
     */
    claim: string;
    /**
     * Event Kind
     */
    event_kind: 'price' | 'earnings' | 'filing' | 'news' | 'macro' | 'other';
    /**
     * Market
     */
    market: 'KR' | 'US';
    /**
     * Mode
     */
    mode: 'prospective' | 'retrospective' | 'synthetic';
    /**
     * Occurred At
     */
    occurred_at: string | null;
    /**
     * Record Id
     */
    record_id: string;
    /**
     * Recorded At
     */
    recorded_at: string;
    /**
     * Retrieved At
     */
    retrieved_at: string;
    /**
     * Source Locator
     */
    source_locator: string;
    /**
     * Source Published At
     */
    source_published_at: string | null;
    /**
     * Symbol
     */
    symbol: string;
    /**
     * Verification
     */
    verification: 'user_supplied' | 'provider_capture' | 'unverified';
};

/**
 * MarketSeries
 */
export type MarketSeries = {
    /**
     * Adjusted
     */
    adjusted: boolean;
    /**
     * Currency
     */
    currency: string;
    /**
     * Id
     */
    id: string;
    /**
     * Interval
     */
    interval: '1m' | '1d';
    /**
     * Points
     */
    points: Array<ObservedCandle>;
    /**
     * Provider
     */
    provider: 'toss';
    /**
     * Symbol
     */
    symbol: string;
};

/**
 * MarketValue
 */
export type MarketValue = {
    /**
     * Amount
     */
    amount: string;
    /**
     * Amountaftercost
     */
    amountAfterCost: string;
    /**
     * Purchaseamount
     */
    purchaseAmount: string;
};

/**
 * MarketView
 */
export type MarketView = {
    /**
     * As Of
     */
    as_of: string;
    /**
     * Event Count
     */
    event_count: number;
    /**
     * Events
     */
    events: Array<MarketEvidenceEvent>;
    /**
     * Excluded Future Capture Ids
     */
    excluded_future_capture_ids: Array<string>;
    /**
     * Generated At
     */
    generated_at: string;
    /**
     * Historical Reproducibility
     */
    historical_reproducibility: false;
    /**
     * Id
     */
    id: string;
    /**
     * Kind
     */
    kind: 'market_observation_view';
    /**
     * Omitted Event Count
     */
    omitted_event_count: number;
    /**
     * Orders Enabled
     */
    orders_enabled: false;
    /**
     * Response Contract Sha256
     */
    response_contract_sha256: string;
    /**
     * Schema Version
     */
    schema_version: 1;
    /**
     * Series
     */
    series: Array<MarketSeries>;
    /**
     * Source Capture Ids
     */
    source_capture_ids: Array<string>;
    /**
     * Total Point Count
     */
    total_point_count: number;
    /**
     * Truncated Point Count
     */
    truncated_point_count: number;
    /**
     * Warnings
     */
    warnings: Array<string>;
};

/**
 * MarketViewRequest
 */
export type MarketViewRequest = {
    /**
     * As Of
     */
    as_of?: string | null;
    /**
     * Capture Ids
     */
    capture_ids: Array<string>;
    /**
     * Max Events
     */
    max_events?: number;
    /**
     * Max Points
     */
    max_points?: number;
};

/**
 * ObservedCandle
 */
export type ObservedCandle = {
    /**
     * Capture Ids
     */
    capture_ids: Array<string>;
    /**
     * Close
     */
    close: string;
    /**
     * Finality
     */
    finality: 'unknown';
    /**
     * High
     */
    high: string;
    /**
     * Id
     */
    id: string;
    /**
     * Last Observed At
     */
    last_observed_at: string;
    /**
     * Low
     */
    low: string;
    /**
     * Observed At
     */
    observed_at: string;
    /**
     * Open
     */
    open: string;
    /**
     * Period End
     */
    period_end: string | null;
    /**
     * Period Start
     */
    period_start: string | null;
    /**
     * Revision Count
     */
    revision_count: number;
    /**
     * Revisions
     */
    revisions: Array<CandleRevision>;
    /**
     * Session Date
     */
    session_date: string | null;
    /**
     * Source Timestamp
     */
    source_timestamp: string;
    /**
     * Volume
     */
    volume: string;
};

/**
 * OmittedReference
 */
export type OmittedReference = {
    /**
     * Reason
     */
    reason: 'future_record' | 'record_limit';
    /**
     * Record Id
     */
    record_id: string;
    /**
     * Reference Id
     */
    reference_id: string;
};

/**
 * OpenOrder
 */
export type OpenOrder = {
    /**
     * Canceledat
     */
    canceledAt?: string | null;
    /**
     * Currency
     */
    currency: string;
    execution: OrderExecution;
    /**
     * Orderamount
     */
    orderAmount?: string | null;
    /**
     * Orderid
     */
    orderId: string;
    /**
     * Ordertype
     */
    orderType: string;
    /**
     * Orderedat
     */
    orderedAt: string;
    /**
     * Price
     */
    price?: string | null;
    /**
     * Quantity
     */
    quantity: string;
    /**
     * Side
     */
    side: string;
    /**
     * Status
     */
    status: string;
    /**
     * Symbol
     */
    symbol: string;
    /**
     * Timeinforce
     */
    timeInForce: string;
};

/**
 * OrderExecution
 */
export type OrderExecution = {
    /**
     * Averagefilledprice
     */
    averageFilledPrice: string | null;
    /**
     * Commission
     */
    commission: string | null;
    /**
     * Filledamount
     */
    filledAmount: string | null;
    /**
     * Filledat
     */
    filledAt: string | null;
    /**
     * Filledquantity
     */
    filledQuantity: string;
    /**
     * Settlementdate
     */
    settlementDate: string | null;
    /**
     * Tax
     */
    tax: string | null;
};

/**
 * OverviewDailyProfitLoss
 */
export type OverviewDailyProfitLoss = {
    amount: CurrencyAmounts;
    /**
     * Rate
     */
    rate: string;
};

/**
 * OverviewMarketValue
 */
export type OverviewMarketValue = {
    amount: CurrencyAmounts;
    amountAfterCost: CurrencyAmounts;
};

/**
 * OverviewProfitLoss
 */
export type OverviewProfitLoss = {
    amount: CurrencyAmounts;
    amountAfterCost: CurrencyAmounts;
    /**
     * Rate
     */
    rate: string;
    /**
     * Rateaftercost
     */
    rateAfterCost: string;
};

/**
 * ProfitLoss
 */
export type ProfitLoss = {
    /**
     * Amount
     */
    amount: string;
    /**
     * Amountaftercost
     */
    amountAfterCost: string;
    /**
     * Rate
     */
    rate: string;
    /**
     * Rateaftercost
     */
    rateAfterCost: string;
};

/**
 * ProposedAction
 */
export type ProposedAction = {
    /**
     * Action
     */
    action: 'buy' | 'add' | 'trim' | 'sell' | 'hold' | 'avoid' | 'research' | 'watch' | 'wait';
    /**
     * Market
     */
    market: 'KR' | 'US' | null;
    /**
     * Quantity
     */
    quantity?: string | null;
    /**
     * Rationale
     */
    rationale: string;
    /**
     * Symbol
     */
    symbol: string | null;
    /**
     * Target Weight
     */
    target_weight?: string | null;
};

/**
 * ResearchAuthor
 */
export type ResearchAuthor = {
    /**
     * Identity Source
     */
    identity_source: 'declared' | 'unknown';
    /**
     * Interface
     */
    interface: 'codex' | 'human';
    /**
     * Model
     */
    model: string | null;
    /**
     * Reasoning Effort
     */
    reasoning_effort: string | null;
};

/**
 * ResearchResponse
 */
export type ResearchResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Record
     */
    record: ({
        kind: 'evidence';
    } & EvidenceRecord) | ({
        kind: 'hypothesis';
    } & HypothesisRecord) | ({
        kind: 'decision';
    } & DecisionRecord) | ({
        kind: 'review';
    } & ReviewRecord);
};

/**
 * ReviewPayload
 */
export type ReviewPayload = {
    /**
     * Decision Id
     */
    decision_id: string;
    /**
     * Judgment
     */
    judgment: 'maintain' | 'revise' | 'retire' | 'unresolved';
    /**
     * New Evidence Ids
     */
    new_evidence_ids: Array<string>;
    /**
     * Observations
     */
    observations: Array<string>;
    /**
     * Replacement Decision Id
     */
    replacement_decision_id?: string | null;
    /**
     * What Changed
     */
    what_changed: string;
};

/**
 * ReviewQueueItem
 */
export type ReviewQueueItem = {
    /**
     * Decision Id
     */
    decision_id: string;
    /**
     * Reasons
     */
    reasons: Array<string>;
    /**
     * Review After
     */
    review_after: string;
    /**
     * Review Ids
     */
    review_ids: Array<string>;
    /**
     * Sizing Validated
     */
    sizing_validated: false;
    /**
     * Status
     */
    status: 'proposed';
    /**
     * Unresolved Questions
     */
    unresolved_questions: Array<string>;
};

/**
 * ReviewRecord
 */
export type ReviewRecord = {
    author: ResearchAuthor;
    /**
     * Kind
     */
    kind: 'review';
    /**
     * Mode
     */
    mode: 'prospective' | 'retrospective' | 'synthetic';
    payload: ReviewPayload;
    /**
     * Recorded At
     */
    recorded_at: string;
    /**
     * Schema Version
     */
    schema_version: 1;
};

/**
 * SelectedAccount
 */
export type SelectedAccount = {
    /**
     * Id
     */
    id: string;
    snapshot: AccountSnapshot;
};

/**
 * SelectedFreshness
 */
export type SelectedFreshness = {
    /**
     * Atomic Account Instant
     */
    atomic_account_instant: false;
    /**
     * Collection Span Seconds
     */
    collection_span_seconds: number;
    /**
     * Completed Age Seconds
     */
    completed_age_seconds: number;
    /**
     * Max Age Seconds
     */
    max_age_seconds: number;
    /**
     * Oldest Observation Age Seconds
     */
    oldest_observation_age_seconds: number;
    /**
     * Reasons
     */
    reasons: Array<string>;
    /**
     * Sizing Validated
     */
    sizing_validated: false;
    /**
     * Snapshot Id
     */
    snapshot_id: string;
    /**
     * Status
     */
    status: 'fresh' | 'stale' | 'future';
};

/**
 * SnapshotSummary
 */
export type SnapshotSummary = {
    /**
     * Account Seq
     */
    account_seq: string;
    /**
     * Account Type
     */
    account_type: string;
    /**
     * Collection Completed At
     */
    collection_completed_at: string;
    /**
     * Collection Started At
     */
    collection_started_at: string;
    /**
     * Holding Count
     */
    holding_count: number;
    /**
     * Id
     */
    id: string;
    /**
     * Open Order Count
     */
    open_order_count: number;
};

/**
 * SourceObservation
 */
export type SourceObservation = {
    /**
     * Capture Id
     */
    capture_id: string;
    /**
     * Endpoint
     */
    endpoint: string;
    /**
     * Observed At
     */
    observed_at: string;
    /**
     * Query
     */
    query: {
        [key: string]: string;
    };
};

/**
 * UnresolvedQuestions
 */
export type UnresolvedQuestions = {
    /**
     * Decision Id
     */
    decision_id: string;
    /**
     * Questions
     */
    questions: Array<string>;
};

/**
 * UnselectedFreshness
 */
export type UnselectedFreshness = {
    /**
     * Max Age Seconds
     */
    max_age_seconds: number;
    /**
     * Sizing Validated
     */
    sizing_validated: false;
    /**
     * Snapshot Id
     */
    snapshot_id: null;
    /**
     * Status
     */
    status: 'not_selected';
};

export type ListAccountSnapshotsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/account-snapshots';
};

export type ListAccountSnapshotsErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Unprocessable Content
     */
    422: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type ListAccountSnapshotsError = ListAccountSnapshotsErrors[keyof ListAccountSnapshotsErrors];

export type ListAccountSnapshotsResponses = {
    /**
     * Successful Response
     */
    200: AccountSnapshotsResponse;
};

export type ListAccountSnapshotsResponse = ListAccountSnapshotsResponses[keyof ListAccountSnapshotsResponses];

export type GetContextData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Snapshot Id
         */
        snapshot_id?: string | null;
        /**
         * Max Records
         */
        max_records?: number;
    };
    url: '/api/v1/context';
};

export type GetContextErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Unprocessable Content
     */
    422: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type GetContextError = GetContextErrors[keyof GetContextErrors];

export type GetContextResponses = {
    /**
     * Successful Response
     */
    200: InvestmentContext;
};

export type GetContextResponse = GetContextResponses[keyof GetContextResponses];

export type HealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/health';
};

export type HealthErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Unprocessable Content
     */
    422: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type HealthError = HealthErrors[keyof HealthErrors];

export type HealthResponses = {
    /**
     * Successful Response
     */
    200: HealthResponse;
};

export type HealthResponse2 = HealthResponses[keyof HealthResponses];

export type ListInvestigationsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/investigations';
};

export type ListInvestigationsErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Unprocessable Content
     */
    422: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
    /**
     * Service Unavailable
     */
    503: ErrorResponse;
};

export type ListInvestigationsError = ListInvestigationsErrors[keyof ListInvestigationsErrors];

export type ListInvestigationsResponses = {
    /**
     * Successful Response
     */
    200: InvestigationList;
};

export type ListInvestigationsResponse = ListInvestigationsResponses[keyof ListInvestigationsResponses];

export type CreateInvestigationData = {
    body: InvestigationCreate;
    path?: never;
    query?: never;
    url: '/api/v1/investigations';
};

export type CreateInvestigationErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Unprocessable Content
     */
    422: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
    /**
     * Service Unavailable
     */
    503: ErrorResponse;
};

export type CreateInvestigationError = CreateInvestigationErrors[keyof CreateInvestigationErrors];

export type CreateInvestigationResponses = {
    /**
     * Successful Response
     */
    200: InvestigationResponse;
};

export type CreateInvestigationResponse = CreateInvestigationResponses[keyof CreateInvestigationResponses];

export type GetInvestigationData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/investigations/{id}';
};

export type GetInvestigationErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Unprocessable Content
     */
    422: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
    /**
     * Service Unavailable
     */
    503: ErrorResponse;
};

export type GetInvestigationError = GetInvestigationErrors[keyof GetInvestigationErrors];

export type GetInvestigationResponses = {
    /**
     * Successful Response
     */
    200: InvestigationResponse;
};

export type GetInvestigationResponse = GetInvestigationResponses[keyof GetInvestigationResponses];

export type PauseInvestigationData = {
    body: InvestigationPause;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/investigations/{id}/pause';
};

export type PauseInvestigationErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Unprocessable Content
     */
    422: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
    /**
     * Service Unavailable
     */
    503: ErrorResponse;
};

export type PauseInvestigationError = PauseInvestigationErrors[keyof PauseInvestigationErrors];

export type PauseInvestigationResponses = {
    /**
     * Successful Response
     */
    200: InvestigationResponse;
};

export type PauseInvestigationResponse = PauseInvestigationResponses[keyof PauseInvestigationResponses];

export type ReviseInvestigationData = {
    body: InvestigationRevise;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/investigations/{id}/revisions';
};

export type ReviseInvestigationErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Unprocessable Content
     */
    422: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
    /**
     * Service Unavailable
     */
    503: ErrorResponse;
};

export type ReviseInvestigationError = ReviseInvestigationErrors[keyof ReviseInvestigationErrors];

export type ReviseInvestigationResponses = {
    /**
     * Successful Response
     */
    200: InvestigationResponse;
};

export type ReviseInvestigationResponse = ReviseInvestigationResponses[keyof ReviseInvestigationResponses];

export type ListJobsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/jobs';
};

export type ListJobsErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Unprocessable Content
     */
    422: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
    /**
     * Service Unavailable
     */
    503: ErrorResponse;
};

export type ListJobsError = ListJobsErrors[keyof ListJobsErrors];

export type ListJobsResponses = {
    /**
     * Successful Response
     */
    200: JobList;
};

export type ListJobsResponse = ListJobsResponses[keyof ListJobsResponses];

export type SubmitJobData = {
    body: JobSubmission;
    path?: never;
    query?: never;
    url: '/api/v1/jobs';
};

export type SubmitJobErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Unprocessable Content
     */
    422: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
    /**
     * Service Unavailable
     */
    503: ErrorResponse;
};

export type SubmitJobError = SubmitJobErrors[keyof SubmitJobErrors];

export type SubmitJobResponses = {
    /**
     * Successful Response
     */
    200: JobResponse;
};

export type SubmitJobResponse = SubmitJobResponses[keyof SubmitJobResponses];

export type JobServiceStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/jobs/status';
};

export type JobServiceStatusErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Unprocessable Content
     */
    422: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
    /**
     * Service Unavailable
     */
    503: ErrorResponse;
};

export type JobServiceStatusError = JobServiceStatusErrors[keyof JobServiceStatusErrors];

export type JobServiceStatusResponses = {
    /**
     * Successful Response
     */
    200: JobServiceStatus;
};

export type JobServiceStatusResponse = JobServiceStatusResponses[keyof JobServiceStatusResponses];

export type GetJobData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/jobs/{id}';
};

export type GetJobErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Unprocessable Content
     */
    422: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
    /**
     * Service Unavailable
     */
    503: ErrorResponse;
};

export type GetJobError = GetJobErrors[keyof GetJobErrors];

export type GetJobResponses = {
    /**
     * Successful Response
     */
    200: JobResponse;
};

export type GetJobResponse = GetJobResponses[keyof GetJobResponses];

export type CancelJobData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/jobs/{id}/cancel';
};

export type CancelJobErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Unprocessable Content
     */
    422: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
    /**
     * Service Unavailable
     */
    503: ErrorResponse;
};

export type CancelJobError = CancelJobErrors[keyof CancelJobErrors];

export type CancelJobResponses = {
    /**
     * Successful Response
     */
    200: JobResponse;
};

export type CancelJobResponse = CancelJobResponses[keyof CancelJobResponses];

export type ListMarketCapturesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/market/catalog';
};

export type ListMarketCapturesErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Unprocessable Content
     */
    422: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type ListMarketCapturesError = ListMarketCapturesErrors[keyof ListMarketCapturesErrors];

export type ListMarketCapturesResponses = {
    /**
     * Successful Response
     */
    200: MarketCatalog;
};

export type ListMarketCapturesResponse = ListMarketCapturesResponses[keyof ListMarketCapturesResponses];

export type GetMarketViewData = {
    body: MarketViewRequest;
    path?: never;
    query?: never;
    url: '/api/v1/market/view';
};

export type GetMarketViewErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Unprocessable Content
     */
    422: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type GetMarketViewError = GetMarketViewErrors[keyof GetMarketViewErrors];

export type GetMarketViewResponses = {
    /**
     * Successful Response
     */
    200: MarketView;
};

export type GetMarketViewResponse = GetMarketViewResponses[keyof GetMarketViewResponses];

export type GetResearchData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/research/{id}';
};

export type GetResearchErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Unprocessable Content
     */
    422: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type GetResearchError = GetResearchErrors[keyof GetResearchErrors];

export type GetResearchResponses = {
    /**
     * Successful Response
     */
    200: ResearchResponse;
};

export type GetResearchResponse = GetResearchResponses[keyof GetResearchResponses];
